services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin # Change this
      - MINIO_SECRET_KEY=password # Change this
      - MINIO_BUCKET=images # Change this
      - MINIO_USESSL=false
    depends_on:
      - minio

  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z-cpuv1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin # Change this
      - MINIO_ROOT_PASSWORD=password # Change this
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
